name: oci-image-build
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * 1'

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Builder
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Container Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Container Image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: docker.io/thomaschampagne/masquarade:latest
